version: 2

defaults: &defaults
  working_directory: ~/ccr
  docker:
    - image: circleci/node:8.12

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies from offline mirror
          command: yarn --offline
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Run Continuous Integration checks
          command: yarn ci-check
